language: python
python:
  - "3.6"
  - "3.5"
  - "2.7"
script:
  - "python setup.py test"
  - "py.test tests/ -v --cov pycmx --cov-report term-missing"
install:
  - "pip install setuptools"
before_install:
  - "pip install coverage"
  - "pip install codecov"
after_success:
  - "codecov"
